name: Build Group3r

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1
      
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5
      
    - name: Setup .NET Framework
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'
        
    - name: Restore NuGet packages
      run: nuget restore Group3r.sln
      
    - name: Build solution
      run: msbuild Group3r.sln /p:Configuration=Release /p:Platform="Any CPU"
      
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Group3r-Release
        path: |
          Group3r/bin/Release/*.exe
          Group3r/bin/Release/*.dll
          Group3r/bin/Release/*.config
        if-no-files-found: error
        
    - name: Upload JSON example
      uses: actions/upload-artifact@v4
      with:
        name: JSON-Examples
        path: |
          JSON_OUTPUT_README.md
          example_json_output.json 