name: Release Group3r

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: windows-2019
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1
      
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5
      
    - name: Install .NET Framework 4.5.1 Developer Pack
      run: choco install netfx-4.5.1-devpack -y
      shell: cmd
      
    - name: Restore NuGet packages
      run: nuget restore Group3r.sln
      
    - name: Build solution
      run: msbuild Group3r.sln /p:Configuration=Release /p:Platform="Any CPU"
      
    - name: Create release package
      run: |
        mkdir release-package
        copy Group3r\bin\Release\*.exe release-package\
        copy Group3r\bin\Release\*.dll release-package\
        copy Group3r\bin\Release\*.config release-package\
        copy JSON_OUTPUT_README.md release-package\
        copy example_json_output.json release-package\
        copy README.md release-package\
        
    - name: Archive release package
      run: |
        cd release-package
        tar -czf ../Group3r-${{ github.ref_name }}.tar.gz *
        cd ..
        
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        name: Group3r ${{ github.ref_name }}
        body: |
          ## Changes in ${{ github.ref_name }}
          
          ### JSON Output Support Added
          - Added support for JSON output format using `-p json` option
          - Enhanced integration capabilities with other security tools
          - Complete preservation of GPO analysis data in structured format
          
          ### Usage
          ```bash
          # For JSON output
          Group3r.exe -p json -s -y "C:\Path\To\SYSVOL"
          
          # For default nice output  
          Group3r.exe -s -y "C:\Path\To\SYSVOL"
          ```
          
          See JSON_OUTPUT_README.md for detailed documentation.
        draft: false
        prerelease: false
        files: Group3r-${{ github.ref_name }}.tar.gz 